### ISSUE TITLE
Release versioning and ember 4 readiness

### ISSUE THREAD

**Issue by johanrd** [nickschot/ember-mobile-menu#240]
Hi. 

`ember install ember-mobile-menu` installs the [latest release](https://github.com/nickschot/ember-mobile-menu/tags) from npm. `v2.1.1` is quite far behind master (with quite some outdated dependencies).

Especially `ember-concurrency` needs an update to support ember 4. (`master` may actually also need an update to `ember-concurrency v2.2.0`). 

Not sure about the plans/status regarding new releases and/or supporting ember 4, so asking here before making possible PRs, @nickschot.

**Comment by nickschot** [comment]
Master was mostly ready for Ember 4 already, we were running into some issues regarding ember-cli-addon-docs breaking CI which have been fixed since. I'll see if I can do a pre-release soon. We'll need some more work to be able to support Embroider as well.

**Comment by nickschot** [comment]
v3 beta release published! Let me know if you run into anything.

**Comment by johanrd** [comment]
great, thanks!
