### ISSUE TITLE
Add fixed width mode for desktop

### ISSUE THREAD

**Issue by nickschot** [nickschot/ember-mobile-menu#25]
I've been thinking of a way to improve the usability of this addon on desktop browsers. I'm thinking of the following:

* Should park the sidebar next to the content.
* Remove any position fixed markup so that it becomes part of the normal flow.
* Remove the mask.
* Gestures should be disabled in this mode.

I'm aware this does not cover all use cases (yet?). Input is welcome!

_To be considered:_ a mode where the sidebar pushes the content (like on emberlcear.io. cc @nullvoxpopuli ) where gestures can still be enabled (i.e. for ipad use). The downside of this mode (which I have used in the past too) is that it causes many many reflows resulting in a degraded framerate for the duration of the animation. I used to partially cover this up by delaying the resize of the main content until after the sidebar transition is done. This still gives good animated feel, but has better performance.

**Comment by NullVoxPopuli** [comment]
what sorts of animations are you using where there is degraded framerate?
we *could* say that if someone wants to use a push behavior, they should be aware that many reflows will cause sub-par UX. 

Is there a way we can throw the ember-mobile-menu in the docs app? so we can implement / try out a bunch of implementations?

**Comment by nickschot** [comment]
It's already hidden in the docs app :yum: slide from the left in responsive mode.

It's not really the animation causing the degraded performance, it's the (amount of) content that needs to be reflowed. Emberclear also shows this when you open/close the sidebar on a smaller screen.

Another thing I'd like to add is support for embedded the menu within a certain element instead of just the app root, but that needs some more work. This will also allow to greatly enhance the docs with embedded examples...

**Comment by NullVoxPopuli** [comment]
> Emberclear also shows this when you open/close the sidebar on a smaller screen.

gasp! I must fix. which screen?

> It's already hidden in the docs app yum slide from the left in responsive mode.
![image](https://user-images.githubusercontent.com/199018/55412473-7ec55500-5535-11e9-9db3-49772c394853.png)

??? Do my eyes deceive me? I'm not seeing it anywhere? does it require gestures? (my psuedo gestures did nothing)

> Another thing I'd like to add is support for embedded the menu within a certain element instead of just the app root, but that needs some more work. This will also allow to greatly enhance the docs with embedded examples...

yeah! that's what I was thinkin' with the docs site.

**Comment by nickschot** [comment]
I now remember that I was trying it in safari... which meant I was using an older version of emberclear as the newer version breaks as Safari has no support for IntersectionObserver. I'll check again in another browser!

Ya, drag from the left in responsive mode (chrome/opera at least, I am not sure if/how firefox emulates this. Safari cannot.).

**Comment by NullVoxPopuli** [comment]
> Safari has no support for IntersectionObserver
:cry: 

> Ya, drag from the left in responsive mode (chrome/opera at least, I am not sure if/how firefox emulates this. Safari cannot.).

![image](https://user-images.githubusercontent.com/199018/55412935-538f3580-5536-11e9-8670-55d5f974d429.png)

:D

the initial touch target could be bigger. but cool. I like this

**Comment by nickschot** [comment]
Ya! It's configurable. By default its configured for mobile "edge" drag which amounts to 15px.

**Comment by nickschot** [comment]
This is made far easier to implement now that #29 has landed.
