### ISSUE TITLE
[3.0.0-beta.3] Cannot read properties of undefined (reading 'extend') at link-to.js 

### ISSUE THREAD

**Issue by johanrd** [nickschot/ember-mobile-menu#267]
When running an app with `ember-mobile-menu 3.0.0-beta.3` from `embroider 1.5.0` and `ember-source 4.3.0`, I get the following error: 

```
TypeError: Cannot read properties of undefined (reading 'extend') at 
eval (webpack://webapp/./node_modules/ember-mobile-menu/components/mobile-menu/link-to.js?:15:143)
```
    
Maybe be related to [#229](https://github.com/nickschot/ember-mobile-menu/pull/229)? or some build / package.json entanglement happening with the recent migration to monorepo? (I see there is a `package.json` both in root and in `/addon`). Please tell me if you are not able to reproduce – I'll try to create a minimal reproduction.

**Comment by nickschot** [comment]
I think it may be this https://github.com/emberjs/ember-legacy-built-in-components/pull/9#issuecomment-1014780817 . Do you have older embroider deps in your lock file? You could try to add a resolution/override for them.

**Comment by johanrd** [comment]
OK, thanks, yes. Was fixed by deleting and recreating my lock file. Thanks!
