### ISSUE TITLE
Fix ember-cli v5 support

### ISSUE THREAD

**Issue by nickschot** [nickschot/ember-mobile-menu#678]
It appears this line does no longer work:

https://github.com/nickschot/ember-mobile-menu/blob/master/addon/index.js#L13

**Comment by johanrd** [comment]
Great! Thanks for the fix:tada:

Perhaps silly question: I fail to install the addon directly from master with pnpm (perhaps because of the monorepo structure):
```
pnpm install github:nickschot/ember-mobile-menu#8a54267fcac3d6562969b4b59f79525aeb8c14f7
ERR_PNPM_MISSING_PACKAGE_NAME  Can't install github:nickschot/ember-mobile-menu#8a54267fcac3d6562969b4b59f79525aeb8c14f7: Missing package name
```

When using something like [gitpkg.vercel.app](https://gitpkg.vercel.app/), it gets installed from the correct commit in /addon, but I get the following error when running `ember serve`:
```
pnpm install 'https://gitpkg.now.sh/nickschot/ember-mobile-menu/addon?master'
…
ember serve
Cannot find module './vendor/ember-mobile-menu.css' from '/app-dir/node_modules/.embroider/rewritten-packages/@embroider/synthesized-vendor'
```

Does it require a release to npm? 
thanks!

**Comment by nickschot** [comment]
> Great! Thanks for the fix🎉
> 
> Perhaps silly question: I fail to install the addon directly from master with pnpm (perhaps because of the monorepo structure):
> 
> ```
> pnpm install github:nickschot/ember-mobile-menu#8a54267fcac3d6562969b4b59f79525aeb8c14f7
> ERR_PNPM_MISSING_PACKAGE_NAME  Can't install github:nickschot/ember-mobile-menu#8a54267fcac3d6562969b4b59f79525aeb8c14f7: Missing package name
> ```
> 
> When using something like [gitpkg.vercel.app](https://gitpkg.vercel.app/), it gets installed from the correct commit in /addon, but I get the following error when running `ember serve`:
> 
> ```
> pnpm install 'https://gitpkg.now.sh/nickschot/ember-mobile-menu/addon?master'
> …
> ember serve
> Cannot find module './vendor/ember-mobile-menu.css' from '/app-dir/node_modules/.embroider/rewritten-packages/@embroider/synthesized-vendor'
> ```
> 
> Does it require a release to npm? thanks!

Yeah, we need a release! I was waiting a bit for all renovatebot updates to propagate. I'll do a release ASAP.

**Comment by nickschot** [comment]
I've made a pre-release (4.0.0-beta.0) so we can make sure it actually works in all situations. If it does, I'll just re-release as stable 👍

**Comment by johanrd** [comment]
great, thanks! `4.0.0-beta.0` seems to work well from my initial testing.
