### ISSUE TITLE
Menu in position relative element

### ISSUE THREAD

**Issue by candunaj** [nickschot/ember-mobile-menu#94]
Hi,
In demo page is menu shown in like div rectangle. I would like to show menu in position relative div but it is always shown over whole page. How can I achieve it?

**Comment by nickschot** [comment]
Hi! You probably want to enable embedded mode. Please see https://nickschot.github.io/ember-mobile-menu/docs/components/menu-wrapper#embedded-menu on how to do that. Let me know if you have any more questions :)

**Comment by candunaj** [comment]
Hi,
i have used embed={{true}} and it works nice. I somehow missed that setting in documentation. Very nice component. Thank you for your help.
