### ISSUE TITLE
Argument to set class on the menu mask and tray

### ISSUE THREAD

**Issue by knownasilya** [nickschot/ember-mobile-menu#96]
Currently using `<MobileMenu class='...'>` sets it on the container. I'd love to use tailwind to style the tray.

**Comment by nickschot** [comment]
What kind of styling do you imagine needing for the tray? Technically it's purely meant as a container element as it's used in calculations etc. so you'd put styled content in it.

The shadow or opacity/blur are the only things I can think of then (as long as you don't use the drag based shadow) hmmmm.... might be useful in that case. I'll have a think about how we could add this. Next release is likely going to be breaking too so we might shake things up a bit to make it possible if that's nicer.
